### ISSUE TITLE
Raspberry Pi Compatibility

### ISSUE THREAD

**Issue by dgsmith** [tlackemann/hubert#2]
This project is amazing, but my home server is a headless Raspberry Pi Zero. It seems that currently the Docker images are only compiled for x86/x64, is there a way to cross compile for arm? Thanks!
![screen shot 2016-02-17 at 6 21 19 pm](https://cloud.githubusercontent.com/assets/723780/13131868/4e4c1b9e-d5a3-11e5-9b70-0fafb472c7ad.png)

output of `uname -a`

    Linux raspberrypi 4.1.17+ #838 Tue Feb 9 12:57:10 GMT 2016 armv6l GNU/Linux

**Comment by tlackemann** [comment]
Thank you!

I'm currently experimenting with a branch to slim down the Docker containers, I'll see what work it would take to have a cross-compiled version for the Pi (I have one laying around I can try it out on). The only problem I see running into is compiling Cassandra and RabbitMQ. I'm pretty positive Node and Python run on ARM just fine. I should have some time this weekend to take a look.

Will keep you updated!

**Comment by dgsmith** [comment]
Thanks for the reply! Back when I posted this I actually had no idea what Docker was haha. After lots of digging, I've found some (hopefully) Raspberry Pi compatible Docker containers on the hub for Cassandra and RabbitMQ. I've edited the Dockerfiles and am trying them out right now!

I was also able to independently install Cassandra and RabbitMQ on my RPi so if those don't work, potentially a new container could be created...

Links for containers:

[rpi-cassandra](https://hub.docker.com/r/taivokasper/rpi-cassandra/)

[rpi-node](https://hub.docker.com/r/hypriot/rpi-node/)

[rpi-rabbitmq](https://hub.docker.com/r/sysrun/rpi-rabbitmq/)

**Comment by tlackemann** [comment]
I've tried playing around with some of the new containers but it's becoming a bit of a major refactor to support the Raspberry Pi. I'm working on a new version of this that will use 100% less Docker (as it's a huge application for such a relatively simple application.) Unfortunately the phrase "never underestimate your ability to over-architect a simple problem" rings painfully true here.

I'll keep you updated when I roll out the new version! For now I'm going to close this in favor of not supporting the Raspberry Pi at the moment (but please, if you feel at all interested to take a shot at this I'm happy to review a pull request!)
